# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fallout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='actif ?'),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_player',
            field=models.BooleanField(db_index=True, default=False, verbose_name='joueur ?'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('human', 'humain'), ('ghoul', 'ghoule'), ('super_mutant', 'super-mutant'), ('deathclaw', 'écorcheur'), ('robot', 'robot'), ('animal', 'animal')], db_index=True, default='human', max_length=12, verbose_name='race'),
        ),
    ]
