# Generated by Django 2.1.7 on 2019-03-18 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fallout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="date")),
                ("game_date", models.DateTimeField(blank=True, null=True, verbose_name="date en jeu")),
                ("text", models.TextField(blank=True, verbose_name="texte")),
                ("private", models.BooleanField(default=False, verbose_name="privé ?")),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="fallout.Character",
                        verbose_name="personnage",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="joueur",
                    ),
                ),
            ],
            options={
                "verbose_name": "journal",
                "verbose_name_plural": "journaux",
            },
        ),
    ]
