# Generated by Django 5.0.1 on 2024-01-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fallout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="money",
            field=models.PositiveIntegerField(default=0, verbose_name="argent"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="money_loot",
            field=models.PositiveIntegerField(default=0, verbose_name="argent à piller"),
        ),
    ]
