# Generated by Django 5.1.1 on 2024-09-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fallout", "0003_xp_in_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="is_visible",
            field=models.BooleanField(db_index=True, default=False, verbose_name="visible ?"),
        ),
    ]
