# Generated by Django 5.1.4 on 2024-12-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fallout", "0004_visible_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="enable_levelup",
            field=models.BooleanField(default=False, verbose_name="montée de niveau ?"),
        ),
        migrations.AddField(
            model_name="character",
            name="enable_logs",
            field=models.BooleanField(default=False, verbose_name="active le journal ?"),
        ),
        migrations.AddField(
            model_name="character",
            name="enable_stats",
            field=models.BooleanField(default=False, verbose_name="active les stats ?"),
        ),
    ]
