# Generated by Django 5.1.4 on 2025-01-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fallout", "0005_features"),
    ]

    operations = [
        migrations.RenameField(
            model_name="effect",
            old_name="duration",
            new_name="min_duration",
        ),
        migrations.AlterField(
            model_name="effect",
            name="min_duration",
            field=models.DurationField(blank=True, null=True, verbose_name="durée d'effet min."),
        ),
        migrations.AddField(
            model_name="effect",
            name="max_duration",
            field=models.DurationField(blank=True, null=True, verbose_name="durée d'effet max."),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="min_money",
            field=models.PositiveIntegerField(default=0, verbose_name="argent min."),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="max_money",
            field=models.PositiveIntegerField(default=0, verbose_name="argent max."),
        ),
    ]
