# Generated by Django 5.1.4 on 2025-01-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fallout", "0006_more_randomness"),
    ]

    operations = [
        migrations.AddField(
            model_name="effect",
            name="controlled",
            field=models.BooleanField(default=False, verbose_name="contrôlable ?"),
        ),
    ]
