# Generated by Django 5.1.4 on 2025-02-03 09:36

import django.db.models.deletion
from django.db import migrations, models


def fix_damage_history_source(apps, schema_editor):
    DamageHistory = apps.get_model("fallout", "DamageHistory")
    DamageHistory.objects.all().update(source=None)


class Migration(migrations.Migration):

    dependencies = [
        ("fallout", "0007_controlled_effect"),
    ]

    operations = [
        migrations.AlterField(
            model_name="damagehistory",
            name="source",
            field=models.CharField(
                max_length=200,
                blank=True,
                null=True,
                verbose_name="source",
            ),
        ),
        migrations.RunPython(
            code=fix_damage_history_source,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="damagehistory",
            name="reason",
            field=models.TextField(blank=True, verbose_name="raison"),
        ),
        migrations.AddField(
            model_name="fighthistory",
            name="reason",
            field=models.TextField(blank=True, verbose_name="raison"),
        ),
        migrations.AddField(
            model_name="rollhistory",
            name="reason",
            field=models.TextField(blank=True, verbose_name="raison"),
        ),
        migrations.AlterField(
            model_name="damagehistory",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fallout.effect",
                verbose_name="source",
            ),
        ),
    ]
