# Generated by Django 3.1.2 on 2020-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fallout", "0012_player_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="name_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="character",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="character",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="character",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="character",
            name="name_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="character",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="character",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="effect",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="effect",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="effect",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="effect",
            name="name_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="effect",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="effect",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="item",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="item",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="item",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="item",
            name="name_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="item",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="item",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="name_fr",
            field=models.CharField(max_length=200, null=True, verbose_name="nom"),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="title_en",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
        migrations.AddField(
            model_name="loottemplate",
            name="title_fr",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="titre"),
        ),
    ]
