# Generated by Django 4.1.7 on 2023-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fallout", "0017_money_in_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="loot_on_death",
            field=models.BooleanField(default=True, verbose_name="butin au décès ?"),
        ),
    ]
